import { Short_Stack } from "next/font/google";
// import "./globals.css";

const shortStack = Short_Stack({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={shortStack.className} style={{ margin: 0 }}>
        {children}
      </body>
    </html>
  );
}
